/**
 * roadmap.model.js
 * -----------------------------------------
 * The sequenced, staged learning plan generated by the Roadmap Engine.
 * `stages` is embedded per the approved database design: bounded count
 * (typically 3-8), always read together as the full roadmap view,
 * never queried independently across users. Fine-grained per-course
 * completion tracking lives in the separate `progress` collection
 * (Phase 9) to isolate write-heavy checkbox-tick operations from this
 * comparatively stable structural document.
 */

const mongoose = require('mongoose');

const { Schema } = mongoose;

const ROADMAP_STATUSES = ['notStarted', 'inProgress', 'completed', 'abandoned'];
const STAGE_STATUSES = ['locked', 'unlocked', 'inProgress', 'completed'];
const UNLOCK_CONDITIONS = ['previousStageComplete', 'none'];

const stageSchema = new Schema(
  {
    stageId: { type: String, required: true },
    title: { type: String, required: true },
    order: { type: Number, required: true },
    estimatedDurationWeeks: { type: Number, required: true, min: 1 },
    linkedCourseIds: { type: [{ type: Schema.Types.ObjectId, ref: 'Course' }], default: [] },
    linkedSkillIds: { type: [{ type: Schema.Types.ObjectId, ref: 'SkillTaxonomy' }], default: [] },
    status: { type: String, enum: STAGE_STATUSES, default: 'locked' },
    unlockCondition: { type: String, enum: UNLOCK_CONDITIONS, default: 'previousStageComplete' },
  },
  { _id: false }
);

const roadmapSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    careerPathId: {
      type: Schema.Types.ObjectId,
      ref: 'CareerPath',
      required: true,
    },
    recommendationId: {
      type: Schema.Types.ObjectId,
      ref: 'Recommendation',
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    stages: {
      type: [stageSchema],
      required: true,
      validate: {
        validator: (arr) => arr.length > 0,
        message: 'A roadmap must contain at least one stage',
      },
    },
    estimatedTotalDurationWeeks: {
      type: Number,
      required: true,
      min: 1,
    },
    status: {
      type: String,
      enum: ROADMAP_STATUSES,
      default: 'notStarted',
    },
    currentStageIndex: {
      type: Number,
      default: 0,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

roadmapSchema.index({ userId: 1, isActive: 1 });
roadmapSchema.index({ userId: 1, createdAt: -1 });

const Roadmap = mongoose.model('Roadmap', roadmapSchema);

module.exports = Roadmap;